---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
base-image: ghcr.io/ublue-os/bazzite-deck
description: Max's Bazzite Image
image-version: stable
name: bluemax

modules:
  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - com.github.zocker_160.SyncThingy
          - com.steamgriddb.steam-rom-manager
          - io.github.ryubing.Ryujinx
          - net.retrodeck.retrodeck
  - type: script
    snippets:
      # cloudflared requires this directory during installation.
      - "mkdir -p /usr/local/bin"
  - type: dnf
    install:
      packages:
        - cloudflared
        - kde-partitionmanager
        - sunshine
    remove:
      packages:
        - "*fcitx5*"
        - "*rom-properties*"
        - filelight
        - gnome-disk-utility
        - kfind
        - "krdc*"
        - kwrite
        - "libime*"
        - webapp-manager
    repos:
      copr:
        - pvermeer/sunshine
      files:
        - https://pkg.cloudflare.com/cloudflared.repo
  - type: script
    scripts:
      - install-polaris.sh
  - type: script
    snippets:
      - |
        rm -f /usr/share/applications/bazzite-documentation.desktop \
          /usr/share/applications/bbrew.desktop \
          /usr/share/applications/discourse.desktop \
          /usr/share/applications/org.kde.kdebugsettings.desktop \
          /usr/share/applications/steam.desktop
  - type: signing
