---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
base-image: ghcr.io/ublue-os/bazzite-deck
description: Max's Bazzite Image
image-version: stable
name: bluemax

modules:
  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - com.github.zocker_160.SyncThingy
          - com.steamgriddb.steam-rom-manager
          - io.github.ryubing.Ryujinx
          - net.retrodeck.retrodeck
  - type: script
    snippets:
      # cloudflared requires this directory during installation.
      - "mkdir -p /usr/local/bin"
  - type: dnf
    install:
      packages:
        - cloudflared
        - https://github.com/papi-ux/polaris/releases/download/v1.4.13/Polaris-fedora%OS_VERSION%-x86_64.rpm
        - kde-partitionmanager
    remove:
      packages:
        - "*fcitx5*"
        - "*rom-properties*"
        - filelight
        - gnome-disk-utility
        - kfind
        - "krdc*"
        - "krfb*"
        - kwrite
        - "libime*"
        - lutris
        - sunshine
        - webapp-manager
    repos:
      files:
        - https://pkg.cloudflare.com/cloudflared.repo
  - type: files
    files:
      - destination: /
        source: system
  - type: script
    snippets:
      - |
        for desktop_entry in \
          /usr/share/applications/bazzite-documentation.desktop \
          /usr/share/applications/bbrew.desktop \
          /usr/share/applications/discourse.desktop \
          /usr/share/applications/org.kde.kdebugsettings.desktop \
          /usr/share/applications/steam.desktop; do
          desktop-file-edit --set-key=NoDisplay --set-value=true "$desktop_entry"
        done
  - type: initramfs
  - type: script
    snippets:
      - |
        set -o pipefail
        for initramfs_image in /usr/lib/modules/*/initramfs.img; do
          lsinitrd --file usr/lib/firmware/edid/streaming.bin "$initramfs_image" |
            cmp /usr/lib/firmware/edid/streaming.bin -
        done
  - type: signing
