---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
base-image: ghcr.io/ublue-os/bazzite-deck
description: Max's Bazzite Image
image-version: latest
name: bluemax
modules:
  - type: rpm-ostree
    install:
      - incus
      - incus-client
      - kde-partitionmanager
    remove:
      - fcitx5-chinese-addons
      - fcitx5-hangul
      - fcitx5-mozc
      - gnome-disk-utility
      - hhd
      - hhd-ui
      - kcm-fcitx5
      - krdc
      - kwrite
      - ptyxis
      - rom-properties-kf6
      - webapp-manager
  - type: systemd
    system:
      enabled:
        - incus.service
  - type: signing
