---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
base-image: ghcr.io/ublue-os/bazzite-deck
description: Max's Bazzite Image
image-version: latest
name: bluemax
modules:
  - type: default-flatpaks
    configurations:
      - install:
          - com.github.zocker_160.SyncThingy
          - com.steamgriddb.steam-rom-manager
          - io.github.ryubing.Ryujinx
          - net.retrodeck.retrodeck
  - type: dnf
    install:
      packages:
        - incus
        - incus-client
        - kde-partitionmanager
    remove:
      packages:
        - "*fcitx5*"
        - "*rom-properties*" 
        - "hhd*"
        - "krdc*"
        - "krfb*"
        - "libime*"
        - filelight
        - gnome-disk-utility
        - kfind
        - kwrite
        - ptyxis
        - webapp-manager
    replace:
      - from-repo: copr:copr.fedorainfracloud.org:pvermeer:sunshine
        packages:
          - old: Sunshine
            new: sunshine
    repos:
      copr:
        - pvermeer/sunshine
  - type: script
    snippets:
      - "curl -Lo /usr/bin/cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64"
      - "chmod +x /usr/bin/cloudflared"
      - "rm -f /usr/share/applications/bazzite-documentation.desktop"
      - "rm -f /usr/share/applications/bbrew.desktop"
      - "rm -f /usr/share/applications/discourse.desktop"
      - "rm -f /usr/share/applications/org.kde.kdebugsettings.desktop"
      - "rm -rf /usr/share/applications/steam"
  - type: systemd
    system:
      enabled:
        - incus.service
  - type: signing
