---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
base-image: ghcr.io/ublue-os/bazzite-deck
description: Max's Bazzite Image
image-version: latest
name: bluemax
modules:
  - type: rpm-ostree
    install:
      - incus
      - incus-client
      - kde-partitionmanager
    remove:
      - gnome-disk-utility
      - ptyxis
      - hhd
      - hhd-ui
  - type: systemd
    system:
      enabled:
        - incus.service
        - incus-lxcfs.service
  - type: signing
