name: BlueBuild

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "00 06 * * *"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  bluebuild:
    name: Build custom image
    runs-on: ubuntu-latest
    steps:
      - name: Build image
        uses: blue-build/github-action@v1.13.0
        with:
          cosign_private_key: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' && secrets.SIGNING_SECRET || '' }}
          pr_event_number: ${{ github.event.number }}
          push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
          recipe: recipe.yaml
          registry_token: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' && github.token || '' }}
