name: bluebuild

on:
  pull_request:
  push:
    paths-ignore:
      - "**.md"
  schedule:
    - cron:
        "00 06 * * *"
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}

jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - recipe.yml
    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@v1.11
        with:
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          pr_event_number: ${{ github.event.number }}
          recipe: ${{ matrix.recipe }}
          registry_token: ${{ github.token }}
