name: BlueBuild

on:
  push:
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "00 06 * * *"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  bluebuild:
    name: Build custom image
    runs-on: ubuntu-latest
    steps:
      - name: Build image
        uses: blue-build/github-action@v1.12.0
        with:
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          recipe: recipe.yaml
          registry_token: ${{ github.token }}
